name: Build

on:
  push:
    branches: [master, devel]
  pull_request:
    branches: [master, devel]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: pip install cython pytest numpy
      - name: Install MetaWards package
        run: CYTHONIZE=1 python setup.py install
      - name: Clone MetaWards data
        run: git clone https://github.com/metawards/MetaWardsData
      - name: Run tests
        run: METAWARDSDATA=./MetaWardsData pytest tests
      - name: Install Sphinx
        run: pip install sphinx sphinx_issues sphinx_rtd_theme
        if: matrix.python-version == 3.8
      - name: Build documentation
        working-directory: ./doc
        run: make html
        if: matrix.python-version == 3.8
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
        if: matrix.python-version == 3.8
      - name: Update website files
        working-directory: ./gh-pages
        run: cp -r ${{ github.workspace }}/doc/build/html/* .
        if: matrix.python-version == 3.8
      - name: Commit website changes
        working-directory: ./gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -a -m "Update website."
        if: matrix.python-version == 3.8
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'gh-pages'
          directory: 'gh-pages'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.python-version == 3.8
