name: Build and test

on:
  push:
    branches: [master, devel]
  pull_request:
    branches: [master, devel]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install libgsl-dev
        run: sudo apt-get install libgsl-dev
      - name: Install Python dependencies
        run: pip install cython numpy pytest
      - name: Install pygsl
        run: pip install pygsl
      - name: Install MetaWards package
        run: CYTHONIZE=1 python setup.py install
      - name: Clone MetaWards data
        run: git clone https://github.com/chryswoods/MetaWardsData
      - name: Run tests
        run: METAWARDSDATA=./MetaWardsData pytest tests
